# test_graph.py

import os
from dotenv import load_dotenv

# Ensure environment variables (like OPENAI_API_KEY) are loaded
load_dotenv()

# Import the compiled LangGraph logic
from data_science.agents.quant_agent import intelligence_hub_graph
from langchain_core.messages import HumanMessage

def test_quant_agent_valuation():
    """
    Simulates a user asking a technical financial question to the agent.
    We want to verify if the agent correctly routes to the SQLite database
    and formats the mathematical metric properly.
    """
    print("\n" + "="*50)
    print("Initiating Agentic Hub Test Protocol...")
    print("="*50 + "\n")
    
    # 1. Define the simulated user query
    user_query = "What is the latest calculated USD margin per barrel (3-2-1 crack spread) for the refinery?"
    print(f"User Query: '{user_query}'\n")

    # 2. Define the initial state (the starting memory of the agent)
    initial_state = {
        "messages": [HumanMessage(content=user_query)],
        "current_valuation_context": "The Dangote Refinery is preparing for a June/July 2026 IPO."
    }

    # 3. Stream the execution graph to see the node transitions in real-time
    print("Agent Reasoning Flow:")
    
    # .stream() allows us to see step-by-step what the graph is doing
    for event in intelligence_hub_graph.stream(initial_state):
        # The event dictionary key tells us which node just finished executing
        for node_name, node_output in event.items():
            print(f"\n✅ Node Completed: [{node_name}]")
            
            # Print the message generated by that node
            message = node_output.get("messages", [])[-1]
            
            # If the message is a tool call (requesting database access)
            if hasattr(message, "tool_calls") and message.tool_calls:
                 print(f"   -> Thought: 'I need to use a tool to answer this.'")
                 for call in message.tool_calls:
                     print(f"   -> Executing Tool: {call['name']} with arguments: {call['args']}")
                     
            # If the message is the output from a tool
            elif hasattr(message, "name") and message.type == "tool":
                print(f"   -> Tool Output: {message.content}")
                
            # If it's a standard AI text response
            elif message.type == "ai":
                print(f"   -> AI Response: {message.content}")
                
    print("\n" + "="*50)
    print("Test Complete.")
    print("="*50 + "\n")

if __name__ == "__main__":
    test_quant_agent_valuation()