# data_science/agents/quant_agent.py

from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode
import os

# Import the state and tools we just built
from data_science.graph.state import HubAgentState
from data_science.tools.db_tools import tools

# 1. Initialize the LLM and bind our database tools to it
# (Make sure OPENAI_API_KEY is set in your .env file)
# LLM Setup
api_key = os.getenv("OPENROUTER_API_KEY", "")
if not api_key:
    raise ValueError("OPENROUTER_API_KEY environment variable is required when using OpenRouter. Get your free key from https://openrouter.ai/")

model_name = os.getenv(
    "OPENROUTER_MODEL", 
    # "google/gemini-2.0-flash-exp:free",
    "z-ai/glm-4.5-air:free")
llm = ChatOpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key,
    model=model_name,  # Default: Gemini Flash (supports tool calling)
    temperature=0,
    max_retries=5
)

llm_with_tools = llm.bind_tools(tools)

# 2. Define the primary Agent Node
def quant_reasoning_node(state: HubAgentState):
    """
    This node evaluates the conversation history. If the user asks a financial question,
    the LLM will output a 'tool_call' to fetch data. If it already has the data, 
    it synthesizes the final answer.
    """
    messages = state["messages"]
    # The LLM reads the history and decides what to do next
    response = llm_with_tools.invoke(messages)
    
    # We return the new message to be appended to the state
    return {"messages": [response]}

# 3. Define the Router Function (Conditional Edge)
def should_continue(state: HubAgentState):
    """
    Reads the last message generated by the LLM. 
    If the LLM decided to call our SQLite tool, route to the 'tools' node.
    Otherwise, end the cycle and return the answer to the user.
    """
    last_message = state["messages"][-1]
    
    if last_message.tool_calls:
        return "tools"
    return END

# 4. Build the Graph Engine
builder = StateGraph(HubAgentState)

# Add our custom reasoning node
builder.add_node("quant_agent", quant_reasoning_node)

# LangGraph provides a prebuilt ToolNode that safely executes our Python @tool functions
builder.add_node("tools", ToolNode(tools))

# Define the exact flow of the graph
builder.add_edge(START, "quant_agent")

# After the agent thinks, use the router to decide: execute tool OR finish
builder.add_conditional_edges("quant_agent", should_continue)

# After a tool runs, ALWAYS return to the agent so it can read the tool's output
builder.add_edge("tools", "quant_agent")

# Compile the final graph
intelligence_hub_graph = builder.compile()